export const COUNTRIES = [
  { nameAr: "الأردن", dial_code: "+962" },
  { nameAr: "اليمن", dial_code: "+967" },
  { nameAr: "السعودية", dial_code: "+966" },
  { nameAr: "الإمارات", dial_code: "+971" },
  { nameAr: "الكويت", dial_code: "+965" },
  { nameAr: "قطر", dial_code: "+974" },
  { nameAr: "البحرين", dial_code: "+973" },
  { nameAr: "عُمان", dial_code: "+968" },
  { nameAr: "مصر", dial_code: "+20" },
  { nameAr: "المغرب", dial_code: "+212" },
  { nameAr: "الجزائر", dial_code: "+213" },
  { nameAr: "تونس", dial_code: "+216" },
  { nameAr: "ليبيا", dial_code: "+218" },
  { nameAr: "لبنان", dial_code: "+961" },
  { nameAr: "سوريا", dial_code: "+963" },
  { nameAr: "العراق", dial_code: "+964" },
  { nameAr: "فلسطين", dial_code: "+970" },
  { nameAr: "السودان", dial_code: "+249" },
  { nameAr: "الصومال", dial_code: "+252" },
  { nameAr: "جيبوتي", dial_code: "+253" },
  { nameAr: "موريتانيا", dial_code: "+222" },
  { nameAr: "جزر القمر", dial_code: "+269" },
  { nameAr: "الولايات المتحدة", dial_code: "+1" },
  { nameAr: "كندا", dial_code: "+1" },
  { nameAr: "المملكة المتحدة", dial_code: "+44" },
  { nameAr: "ألمانيا", dial_code: "+49" },
  { nameAr: "فرنسا", dial_code: "+33" },
  { nameAr: "إيطاليا", dial_code: "+39" },
  { nameAr: "إسبانيا", dial_code: "+34" },
  { nameAr: "تركيا", dial_code: "+90" },
  { nameAr: "إيران", dial_code: "+98" },
  { nameAr: "باكستان", dial_code: "+92" },
  { nameAr: "الهند", dial_code: "+91" },
  { nameAr: "الصين", dial_code: "+86" },
  { nameAr: "روسيا", dial_code: "+7" },
  { nameAr: "أستراليا", dial_code: "+61" },
  { nameAr: "البرازيل", dial_code: "+55" },
  { nameAr: "الأرجنتين", dial_code: "+54" },
  { nameAr: "المكسيك", dial_code: "+52" },
  { nameAr: "اليابان", dial_code: "+81" },
  { nameAr: "كوريا الجنوبية", dial_code: "+82" },
  { nameAr: "ماليزيا", dial_code: "+60" },
  { nameAr: "إندونيسيا", dial_code: "+62" },
  { nameAr: "تايلاند", dial_code: "+66" },
  { nameAr: "جنوب أفريقيا", dial_code: "+27" },
  { nameAr: "نيجيريا", dial_code: "+234" },
  { nameAr: "كينيا", dial_code: "+254" },
  { nameAr: "إثيوبيا", dial_code: "+251" },
  { nameAr: "غانا", dial_code: "+233" },
  { nameAr: "تنزانيا", dial_code: "+255" },
  { nameAr: "أوغندا", dial_code: "+256" },
  { nameAr: "السنغال", dial_code: "+221" },
  { nameAr: "أفغانستان", dial_code: "+93" },
  { nameAr: "ألبانيا", dial_code: "+355" },
  { nameAr: "أندورا", dial_code: "+376" },
  { nameAr: "أنجولا", dial_code: "+244" },
  { nameAr: "أنتيغوا وبربودا", dial_code: "+1-268" },
  { nameAr: "أرمينيا", dial_code: "+374" },
  { nameAr: "النمسا", dial_code: "+43" },
  { nameAr: "أذربيجان", dial_code: "+994" },
  { nameAr: "باهاماس", dial_code: "+1-242" },
  { nameAr: "بنغلاديش", dial_code: "+880" },
  { nameAr: "باربادوس", dial_code: "+1-246" },
  { nameAr: "بيلاروس", dial_code: "+375" },
  { nameAr: "بلجيكا", dial_code: "+32" },
  { nameAr: "بليز", dial_code: "+501" },
  { nameAr: "بنين", dial_code: "+229" },
  { nameAr: "بوتان", dial_code: "+975" },
  { nameAr: "بوليفيا", dial_code: "+591" },
  { nameAr: "البوسنة والهرسك", dial_code: "+387" },
  { nameAr: "بوتسوانا", dial_code: "+267" },
  { nameAr: "بروناي", dial_code: "+673" },
  { nameAr: "بلغاريا", dial_code: "+359" },
  { nameAr: "بوركينا فاسو", dial_code: "+226" },
  { nameAr: "بوروندي", dial_code: "+257" },
  { nameAr: "كمبوديا", dial_code: "+855" },
  { nameAr: "الكاميرون", dial_code: "+237" },
  { nameAr: "الرأس الأخضر", dial_code: "+238" },
  { nameAr: "جمهورية أفريقيا الوسطى", dial_code: "+236" },
  { nameAr: "تشاد", dial_code: "+235" },
  { nameAr: "شيلي", dial_code: "+56" },
  { nameAr: "كولومبيا", dial_code: "+57" },
  { nameAr: "الكونغو", dial_code: "+242" },
  { nameAr: "كوستاريكا", dial_code: "+506" },
  { nameAr: "كرواتيا", dial_code: "+385" },
  { nameAr: "كوبا", dial_code: "+53" },
  { nameAr: "قبرص", dial_code: "+357" },
  { nameAr: "جمهورية التشيك", dial_code: "+420" },
  { nameAr: "الدنمارك", dial_code: "+45" },
  { nameAr: "دومينيكا", dial_code: "+1-767" },
  { nameAr: "جمهورية الدومينيكان", dial_code: "+1-809" },
  { nameAr: "الإكوادور", dial_code: "+593" },
  { nameAr: "السلفادور", dial_code: "+503" },
  { nameAr: "غينيا الاستوائية", dial_code: "+240" },
  { nameAr: "إريتريا", dial_code: "+291" },
  { nameAr: "إستونيا", dial_code: "+372" },
  { nameAr: "إسواتيني", dial_code: "+268" },
  { nameAr: "فيجي", dial_code: "+679" },
  { nameAr: "فنلندا", dial_code: "+358" },
  { nameAr: "جابون", dial_code: "+241" },
  { nameAr: "غامبيا", dial_code: "+220" },
  { nameAr: "جورجيا", dial_code: "+995" },
  { nameAr: "اليونان", dial_code: "+30" },
  { nameAr: "غرينادا", dial_code: "+1-473" },
  { nameAr: "غواتيمالا", dial_code: "+502" },
  { nameAr: "غينيا", dial_code: "+224" },
  { nameAr: "غينيا بيساو", dial_code: "+245" },
  { nameAr: "غيانا", dial_code: "+592" },
  { nameAr: "هايتي", dial_code: "+509" },
  { nameAr: "هندوراس", dial_code: "+504" },
  { nameAr: "المجر", dial_code: "+36" },
  { nameAr: "أيسلندا", dial_code: "+354" },
  { nameAr: "أيرلندا", dial_code: "+353" },
  { nameAr: "إسرائيل", dial_code: "+972" },
  { nameAr: "جامايكا", dial_code: "+1-876" },
  { nameAr: "كازاخستان", dial_code: "+7" },
  { nameAr: "كيريباتي", dial_code: "+686" },
  { nameAr: "كوريا الشمالية", dial_code: "+850" },
  { nameAr: "قرغيزستان", dial_code: "+996" },
  { nameAr: "لاوس", dial_code: "+856" },
  { nameAr: "لاتفيا", dial_code: "+371" },
  { nameAr: "ليسوتو", dial_code: "+266" },
  { nameAr: "ليبيريا", dial_code: "+231" },
  { nameAr: "ليختنشتاين", dial_code: "+423" },
  { nameAr: "ليتوانيا", dial_code: "+370" },
  { nameAr: "لوكسمبورغ", dial_code: "+352" },
  { nameAr: "مدغشقر", dial_code: "+261" },
  { nameAr: "ملاوي", dial_code: "+265" },
  { nameAr: "جزر المالديف", dial_code: "+960" },
  { nameAr: "مالي", dial_code: "+223" },
  { nameAr: "مالطا", dial_code: "+356" },
  { nameAr: "جزر مارشال", dial_code: "+692" },
  { nameAr: "موريشيوس", dial_code: "+230" },
  { nameAr: "ميكرونيزيا", dial_code: "+691" },
  { nameAr: "مولدوفا", dial_code: "+373" },
  { nameAr: "موناكو", dial_code: "+377" },
  { nameAr: "منغوليا", dial_code: "+976" },
  { nameAr: "الجبل الأسود", dial_code: "+382" },
  { nameAr: "موزمبيق", dial_code: "+258" },
  { nameAr: "ميانمار", dial_code: "+95" },
  { nameAr: "ناميبيا", dial_code: "+264" },
  { nameAr: "ناورو", dial_code: "+674" },
  { nameAr: "نيبال", dial_code: "+977" },
  { nameAr: "هولندا", dial_code: "+31" },
  { nameAr: "نيوزيلندا", dial_code: "+64" },
  { nameAr: "نيكاراغوا", dial_code: "+505" },
  { nameAr: "النيجر", dial_code: "+227" },
  { nameAr: "مقدونيا الشمالية", dial_code: "+389" },
  { nameAr: "النرويج", dial_code: "+47" },
  { nameAr: "بالاو", dial_code: "+680" },
  { nameAr: "بنما", dial_code: "+507" },
  { nameAr: "بابوا غينيا الجديدة", dial_code: "+675" },
  { nameAr: "باراغواي", dial_code: "+595" },
  { nameAr: "بيرو", dial_code: "+51" },
  { nameAr: "الفلبين", dial_code: "+63" },
  { nameAr: "بولندا", dial_code: "+48" },
  { nameAr: "البرتغال", dial_code: "+351" },
  { nameAr: "رومانيا", dial_code: "+40" },
  { nameAr: "رواندا", dial_code: "+250" },
  { nameAr: "سانت كيتس ونيفيس", dial_code: "+1-869" },
  { nameAr: "سانت لوسيا", dial_code: "+1-758" },
  { nameAr: "سانت فنسنت والغرينادين", dial_code: "+1-784" },
  { nameAr: "ساموا", dial_code: "+685" },
  { nameAr: "سان مارينو", dial_code: "+378" },
  { nameAr: "ساو تومي وبرينسيب", dial_code: "+239" },
  { nameAr: "صربيا", dial_code: "+381" },
  { nameAr: "سيشيل", dial_code: "+248" },
  { nameAr: "سيراليون", dial_code: "+232" },
  { nameAr: "سنغافورة", dial_code: "+65" },
  { nameAr: "سلوفاكيا", dial_code: "+421" },
  { nameAr: "سلوفينيا", dial_code: "+386" },
  { nameAr: "جزر سليمان", dial_code: "+677" },
  { nameAr: "جنوب السودان", dial_code: "+211" },
  { nameAr: "سريلانكا", dial_code: "+94" },
  { nameAr: "سورينام", dial_code: "+597" },
  { nameAr: "السويد", dial_code: "+46" },
  { nameAr: "سويسرا", dial_code: "+41" },
  { nameAr: "طاجيكستان", dial_code: "+992" },
  { nameAr: "تيمور الشرقية", dial_code: "+670" },
  { nameAr: "توغو", dial_code: "+228" },
  { nameAr: "تونجا", dial_code: "+676" },
  { nameAr: "ترينيداد وتوباغو", dial_code: "+1-868" },
  { nameAr: "تركمانستان", dial_code: "+993" },
  { nameAr: "توفالو", dial_code: "+688" },
  { nameAr: "أوكرانيا", dial_code: "+380" },
  { nameAr: "أوروغواي", dial_code: "+598" },
  { nameAr: "أوزبكستان", dial_code: "+998" },
  { nameAr: "فانواتو", dial_code: "+678" },
  { nameAr: "مدينة الفاتيكان", dial_code: "+379" },
  { nameAr: "فنزويلا", dial_code: "+58" },
  { nameAr: "فيتنام", dial_code: "+84" },
  { nameAr: "زامبيا", dial_code: "+260" },
  { nameAr: "زيمبابوي", dial_code: "+263" }
];
